title: hyperlink.cool
url: https://hyperlink.cool
description: 'hyperlink.cool is a searchable link collection for my fellow Computer Science and Media students at Bauhaus-Univerit√§t Weimar.'

permalink: /:title

include:
  - '.htaccess'
  - '_data'

exclude:
  - 'node_modules'
  - '*.sublime-workspace'

plugins:
  - jekyll-sitemap

kramdown:
  input: GFM
  auto_ids: false

sass:
  style: compressed



color:
  text: '333333'
  background: 'efefef'
  ui: '3756a4'

author:
  mail: 'phrudloff@gmail.com'
  website: 'https://kleinfreund.de'

# compress.html by Anatol Broder (http://jch.penibelst.de)
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
  endings: all
  ignore:
    envs: [development]


defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "redirects"
    values:
      layout: "redirect"
